[package]
name = "logdbg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
cursive = { version = "0.20", features = ["toml"] }
log = "0.4"
env_logger = "0.10"
rand = "0.8"
regex = "1.7"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.3"

[build-dependencies]
cc="*"

[[example]]
name = "dining"

[[example]]
name = "basic"
