[package]
name = "logdbg"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
clap = { version = "4.1", features = ["derive"]}
rand = "0.8"
regex = "1.7"

[[example]]
name = "dining"

[[example]]
name = "basic"
